services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    command: ["start"]
    ports:
      - "8080:8080"
      - "9090:8443"
    volumes:
      - /usr/local/psa/var/modules/letsencrypt/etc/live/keycloak.oliverswienty.de/fullchain.pem:/opt/keycloak/conf/server.crt
      - /usr/local/psa/var/modules/letsencrypt/etc/live/keycloak.oliverswienty.de/privkey.pem:/opt/keycloak/conf/server.key
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      PROXY_ADDRESS_FORWARDING: true
      KC_HOSTNAME_URL: https://keycloak.oliverswienty.de
      KC_HOSTNAME_ADMIN_URL: https://keycloak.oliverswienty.de
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/server.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/server.key
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - ./.data:/var/lib/postgresql/data
